-- Add payment approval workflow columns to income table
ALTER TABLE income ADD COLUMN IF NOT EXISTS payment_mode TEXT DEFAULT NULL;
ALTER TABLE income ADD COLUMN IF NOT EXISTS ref_number TEXT DEFAULT NULL;
ALTER TABLE income ADD COLUMN IF NOT EXISTS payment_date DATE DEFAULT NULL;
ALTER TABLE income ADD COLUMN IF NOT EXISTS status TEXT DEFAULT 'approved';
ALTER TABLE income ADD COLUMN IF NOT EXISTS approved_by TEXT DEFAULT NULL;
ALTER TABLE income ADD COLUMN IF NOT EXISTS approved_at TIMESTAMP DEFAULT NULL;
